### ISSUE TITLE
[home-assistant] Official Docker image

### ISSUE THREAD

**Issue by WyriHaximus** [loeken/helm-charts#1]
Hey while looking for a k8s at home replacement Helm Chart for Home Assistant I ran across yours. It looks pretty much the same, but it is using a self build Docker image. Does your chart also work with the official Home Assistant Docker image?

**Comment by loeken** [comment]
my chart uses bjw-s's library ( which was formerly used by k8s-at-home too )
https://github.com/loeken/docker-home-assistant/blob/main/Dockerfile <- build happens from this dockerfila via github action in same repo.

I havent tested it with the official home assistant docker image yet

**Comment by loeken** [comment]
i ll close this if you need anything else feel free to raise a new ticket

**Comment by WyriHaximus** [comment]
Hi sorry for not responding earlier, had a bit of a rough few weeks. Haven't updated the k8s at home chart I have installed and just injected the latest official image without issues.
