### ISSUE TITLE
index.yaml : 404 Not Found

### ISSUE THREAD

**Issue by speedkup** [loeken/helm-charts#77]
Hi

I wanted to install the rtorrent-flood application from your Helm repository using ArgoCD, but unfortunately, the installation failed.

Here is what I used in ArgoCD:
sources:
  - repoURL: https://github.com/loeken/helm-charts
    targetRevision: '4.8.2'
    chart: rtorrent-flood

And this is the error message I received:
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm pull --destination /tmp/12103458-aaf4-422d-ac7d-f35b890eea6f --version 4.8.2 --repo https://github.com/loeken/helm-charts rtorrent-flood` failed exit status 1: Error: looks like "https://github.com/loeken/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/loeken/helm-charts/index.yaml : 404 Not Found

Indeed, I couldn't find the index.yaml file in the repository.

**Comment by speedkup** [comment]
In the meantime, I realized that this is the Helm chart URL: https://loeken.github.io/helm-charts

However, now I am getting this error message:

Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template rtorrent-flood-helm --namespace mediaserver --kube-version 1.29 --values <path to cached source>/k3s/rtorrent-flood/helm-values.yml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (rtorrent-flood/templates/common.yaml:14:3): server not set Use --debug flag to render out invalid YAML

**Comment by loeken** [comment]
https://loeken.github.io/helm-charts/index.yaml

try this as repo url, a github action here builds this file for helm to consume
