### ISSUE TITLE
Jellyfin - version

### ISSUE THREAD

**Issue by yuval987** [loeken/helm-charts#79]
Hey,
The version in your chart is 10.9.7, but the real version is 10.8.13, why?
Thanks!

**Comment by loeken** [comment]
good question, took me a bit to figure out myself :p

this repo is building the docker image:
https://github.com/loeken/docker-jellyfin/blob/main/Dockerfile

as you can see it installed from apline 3.19 ( https://pkgs.alpinelinux.org/packages?name=jellyfin&branch=v3.19&repo=&arch=&maintainer= ) which has 10.9.8

https://github.com/loeken/docker-jellyfin/commit/a9351e1b3324f74e9cbf867288cb1ccfa8c711ff i now bumbed it to 3.20

so this should give us 10.9.8-r0

when i wrote the tool that updates ( https://github.com/loeken/homelab-updater ) the alpine package version and the actual github version were in sync, now they are not anymore and i am still using the tags in the jellyfin repo to kick off new builds

**Comment by loeken** [comment]
feel free to re-open if you need further info
